name: intl_phone_field
description: A customized Flutter TextFormField to input international phone number along with country code.
version: 2.1.1
repository: https://github.com/vanshg395/intl_phone_field
publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/flags/
